baseURL = "/"
languageCode = "en-us"
title = "The SKD Blog"
theme = "re-terminal"
pagerSize = 5
canonifyURLs = true
relativeURLs = true

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  favicon = "images/blogfavicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.en.params]
    title = "The SKD Blog"
    subtitle = "embedded logs, drivers, bugs and bytes"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "shaunak@datar:~$"
      logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true